# Generated by Django 3.0.8 on 2020-08-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_auto_20200810_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='priority',
            field=models.CharField(choices=[('danger', 'Q1(重要かつ緊急)'), ('warning', 'Q2(重要)'), ('info', 'Q3(緊急)')], max_length=50),
        ),
    ]
