# Generated by Django 3.0.8 on 2020-08-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_auto_20200810_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='duedate',
            field=models.DateField(default='2020-08-23'),
            preserve_default=False,
        ),
    ]
